name: Run argocd-cli

on: 
  push:
  workflow_dispatch:

jobs:
  argocd-cli:
    runs-on: ubuntu-latest
    name: argocd-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./vc-argocd-cli # Uses an action in the root directory
        id: argocd-cli
        with:
          server: cd.govirto.com
          username: ${{ secrets.ARGOCD_LOGIN }}
          password: ${{ secrets.ARGOCD_PASSWORD }}